---
- name: Install Mac packages
  hosts: localhost
  become: false
  vars:
    homebrew_brews:
      - aws-sam-cli
      - aws/tap/copilot-cli
      - aws-vault
      - awscli
      - awscli@1
      - awslogs
      - babashka
      - babashka/brew/neil
      - babashka/brew/bbin
      - borkdude/brew/babashka
      - borkdude/brew/clj-kondo
      - borkdude/brew/jet
      - bat
      - bbin
      - bottom
      - chezmoi
      - choose-rust
      - clojure-lsp
      - colima
      - colordiff
      - coreutils
      - cscope
      - ctags
      - curlie
      - d12frosted/emacs-plus/emacs-plus@29
      - direnv
      - docker
      - dos2unix
      - entr
      - fd
      - fish
      - fzf
      - gh
      - git
      - git-extras
      - git-quick-stats
      - git-secret
      - glow
      - goreleaser/tap/goreleaser
      - graphviz
      - gum
      - hub
      - jid
      - johanhaleby/kubetail/kubetail
      - jq
      - just
      - k9s
      - kubectx
      - kustomize
      - lazygit
      - leiningen
      - mas
      - maven
      - mtr
      - ncdu
      - neovim
      - newsboat
      - nmap
      - nnn
      - podman
      - pulumi/tap/pulumi
      - pwgen
      - reattach-to-user-namespace
      - ripgrep
      - rlwrap
      - rtx
      - sd
      - shellcheck
      - shfmt
      - skhd
      - sqlite
      - starship
      - terminal-notifier
      - tig
      - tmux
      - tmux-xpanes
      - tree
      - watchexec
      - websocat
      - weechat
      - yq
      - youtube-dl
      - zsh
    homebrew_casks:
      - authy
      - disk-inventory-x
      - homebrew/cask-fonts/font-fira-code
      - homebrew/cask-fonts/font-fira-code-nerd-font
      - iina
      - insomnia
      - kitty
      - licecap
      - mtmr
      - notion
      - rapidapi
      - raycast
      - slack
      - spotify
      - todoist
      - visual-studio-code
      - wezterm
      - zprint
  tasks:

    - name:  mise - Upgrade packages
      ansible.builtin.shell: mise upgrade
      register: result

    - debug: msg="{{ result }}"

    - name: Homebrew - updating homebrew
      homebrew:
        update_homebrew: yes
      register: result
      until: result is successful

    - debug: msg="{{ result.msg }}"

    - name: Homebrew - upgrading existing packages
      homebrew:
        upgrade_all: yes
      register: result
      until: result is successful

    - debug: msg="{{ result.msg }} Upgraded {{ result.changed_pkgs }}"

    - name: Homebrew - installing missing packages
      homebrew:
        name: "{{ homebrew_brews }}"
        state: present
        install_options: verbose
      register: result
      until: result is successful

    - debug: msg="{{ result.msg }} -> {{ result.changed_pkgs }}"

    - name: Homebrew - installing missing casks
      homebrew_cask:
        name: "{{ homebrew_casks }}"
        state: present
      register: result
      until: result is successful

    - debug: msg="{{ result.msg }}"
