---
- name: Install Mac packages
  hosts: localhost
  become: false
  vars:
    homebrew_brews: "{{ lookup('file', 'brews').split('\n') }}"
    homebrew_casks: "{{ lookup('file', 'casks').split('\n') }}"
  tasks:
    - name:  mise - Upgrade packages
      ansible.builtin.shell: mise upgrade
      register: result

    - debug: msg="{{ result }}"

    - name: Homebrew - updating homebrew
      homebrew:
        update_homebrew: yes
      register: result
      until: result is successful

    - debug: msg="{{ result.msg }}"

    - name: Homebrew - upgrading existing packages
      homebrew:
        upgrade_all: yes
      register: result
      until: result is successful

    - debug: msg="{{ result.msg }} Upgraded {{ result.changed_pkgs }}"

    - name: Homebrew - installing missing packages
      homebrew:
        name: "{{ homebrew_brews }}"
        state: present
        install_options: verbose
      register: result
      until: result is successful

    - debug: msg="{{ result.msg }} -> {{ result.changed_pkgs }}"

    - name: Homebrew - installing missing casks
      homebrew_cask:
        name: "{{ homebrew_casks }}"
        state: present
      register: result
      until: result is successful

    - debug: msg="{{ result.msg }}"
